### ISSUE TITLE
Java to CPP translation : vector -- indexOf (Object o)

### ISSUE THREAD

**Issue by lublud** [darrivau/GOOL#10]
```java
if(2 == list2.indexOf("titi"))
```
is translated into:
```cpp
if ((2 == list.indexOf("titi") list2 -> indexOf(( new std::string ( "titi" ) ))))
```

In addition to a mistranslation (java code seemed to be copy/paste in the C++ translation), indexOf() does not exist in C++ for vector.

**Comment by darrivau** [comment]
Corrected in the current commit (887db7d) with `std::find(list1->begin(),list1->end(),"tata") - list1->begin()))`
