### ISSUE TITLE
Java to CPP translation : vector -- remove (int index)

### ISSUE THREAD

**Issue by lublud** [darrivau/GOOL#12]
```java
list.remove(0);
```
is translated into:
```cpp
for(std::vector<int>::size_type i = 0; i != list->size(); i++)
{
    if ( boost::any_cast<int>(list->at(i)) == 0 )
    {
        list->erase(list->begin()+i);
        break;
    }
}; 
```
Here, remove(int Index) is seen as remove(Object o) and thus tries to remove the Object - int 0 - instead of the element of index 0.

Should have been:
```cpp
list->erase(list->begin()+0);
```

**Comment by darrivau** [comment]
Corrected in current commit (887db7d) and tested by goolLibraryJavaListToCppVectorTestRemove()
