### ISSUE TITLE
Java -> CPP  : invalid operands of types ‘double’ and ‘double’ to binary ‘operator%’

### ISSUE THREAD

**Issue by Windalfr** [darrivau/GOOL#28]
Error: invalid operands of types ‘double’ and ‘double’ to binary ‘operator%’

In Java,  the operator '%' is allowed for the type double, but in C++, it isn't. 
It's only allowed for the type int.

**Comment by darrivau** [comment]
GoolTestIsPrimary

**Comment by darrivau** [comment]
Corrected in commit 475b781
