### ISSUE TITLE
  Java to CPP translation : vector -- get(int Index)

### ISSUE THREAD

**Issue by lublud** [darrivau/GOOL#7]
Java instruction:
```java
if("tata" == list.get(0))
```
is translated in C++ in:
```cpp
if ((( new std::string ( "tata" ) ) == list->at(0)))
```

However
```cpp
list->at(0)
```
returns the address of element 0 while we expect the content.

**Comment by darrivau** [comment]
This bug is strange as Gool does not translate java list to Cpp list but vector list. Furthermore there is no method "at" for std::list in C++

**Comment by lublud** [comment]
In the C++ translation, list is a vector but kept its name from the java input: it is not a list..

The Java instruction compares strings.
After translation in C++, addresses that can not be equals in such conditions are compared, which is not what we expect there.

The method in which the bug appears can be found here:
https://github.com/lublud/GOOL/blob/ProjectM2_2015/src/gool/test/lib/GoolTestTypeListToVectorCpp.java
line 174: goolLibraryJavaListToCppVectorTestAddGet()
