### ISSUE TITLE
Java to CPP translation : vector -- equals (Object o) 

### ISSUE THREAD

**Issue by lublud** [darrivau/GOOL#9]
```java
if(list.equals(list2))
```
is translated into:
```cpp
if (list -> equals(list2))
```

However, equals() does not exist for vector in C++.

**Comment by darrivau** [comment]
GoolTestTypeListToVectorCpp - TestEquals : ‘class std::vector<std::basic_string<char>*>’ has no member named ‘equals’

**Comment by darrivau** [comment]
Corrected in the current commit (887db7d) with `*list1 == *list2`
